<?php
/**
 * GeneratePress child theme functions and definitions.
 *
 * Add your custom PHP in this file.
 * Only edit this file if you have direct access to it on your server (to fix errors if they happen).
 */
<?php
/**
 * Persian digits helper
 */
function my_fa_digits_map() {
  // Western 0-9 + Arabic-Indic (٠-٩) → Persian (۰-۹)
  return [
    '0'=>'۰','1'=>'۱','2'=>'۲','3'=>'۳','4'=>'۴','5'=>'۵','6'=>'۶','7'=>'۷','8'=>'۸','9'=>'۹',
    '٠'=>'۰','١'=>'۱','٢'=>'۲','٣'=>'۳','٤'=>'۴','٥'=>'۵','٦'=>'۶','٧'=>'۷','٨'=>'۸','٩'=>'۹',
  ];
}

function my_to_persian_digits($str) {
  if ($str === '' || $str === null) return $str;
  return strtr($str, my_fa_digits_map());
}

/**
 * Convert digits in visible HTML text nodes only (not inside tags/attrs).
 * Skips code/pre/script/style/kbd/samp elements.
 */
function my_convert_html_text_nodes_to_fa($html) {
  if ($html === '' || $html === null) return $html;

  // Temporarily extract blocks to skip
  $placeholders = [];
  $skip_tags = '(?:code|pre|script|style|kbd|samp)';
  $html = preg_replace_callback('#<'.$skip_tags.'\b[^>]*>.*?</'.$skip_tags.'>#siu', function($m) use (&$placeholders){
    $key = '%%SKIP'.count($placeholders).'%%';
    $placeholders[$key] = $m[0];
    return $key;
  }, $html);

  // Convert only text between tags: > ... <
  $html = preg_replace_callback('/>([^<]+)</u', function($m){
    return '>' . my_to_persian_digits($m[1]) . '<';
  }, $html);

  // Restore skipped blocks
  if (!empty($placeholders)) {
    $html = strtr($html, $placeholders);
  }

  return $html;
}

/**
 * Frontend filters
 */
function my_enable_persian_digits_filters() {
  if (is_admin()) return; // frontend only

  // Content-like fields (convert only visible text nodes)
  add_filter('the_content', 'my_convert_html_text_nodes_to_fa', 20);
  add_filter('the_excerpt', 'my_convert_html_text_nodes_to_fa', 20);
  add_filter('comment_text', 'my_convert_html_text_nodes_to_fa', 20);
  add_filter('widget_text', 'my_convert_html_text_nodes_to_fa', 20); // classic text widget

  // Plain strings (safe to convert entire string)
  add_filter('the_title', 'my_to_persian_digits', 20);
  add_filter('widget_title', 'my_to_persian_digits', 20);
  add_filter('nav_menu_item_title', 'my_to_persian_digits', 20, 1);

  // Numbers/dates generated by WP
  add_filter('number_format_i18n', 'my_to_persian_digits', 20);
  add_filter('date_i18n', 'my_to_persian_digits', 20);

  // Optional: site name/description (if they contain digits)
  add_filter('bloginfo', 'my_to_persian_digits', 20);
  add_filter('bloginfo_name', 'my_to_persian_digits', 20);
  add_filter('bloginfo_description', 'my_to_persian_digits', 20);
}
add_action('init', 'my_enable_persian_digits_filters');
